name: Update-l10n

on:
  push:
    branches: [master]

jobs:
  update-l10n:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"

      - name: Restore pip cache 💾
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Babel 🌐
        run: |
          pip3 install -U pip
          pip3 install Babel==2.9.0

      - name: Update localization source file 📄
        run: |
          pybabel extract bot.py pdf_bot/ -o locale/pdf_bot.pot
          pybabel update -l locale -i locale/pdf_bot.pot -o locale/en_GB/LC_MESSAGES/pdf_bot.po
          echo NUM_DIFFS=$(git diff --shortstat | egrep -o '[0-9]+ i' | egrep -o '[0-9]+') >> $GITHUB_ENV

      - name: Create Pull Request 🆕
        if: env.NUM_DIFFS > 1
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update localization source file
          branch: update/l10n-source-file
          title: Update localization source file
